version: 2
jobs:
  build:
    working_directory: ~/project
    docker:
      - image: node:7
    steps:
      - checkout
      - restore_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
      - restore_cache:
          name: Restore cache (bower_components)
          key: bower_components-hack1-{{ checksum "bower.json" }
      - run:
          name: Install dependencies
          command: yarn --pure-lockfile
      - run:
          name: Rebuild problematic node modules
          command: npm rebuild node-sass phantomjs-prebuilt
      - save_cache:
          key: node_modules-{{ checksum "yarn.lock" }}
          paths:
            - node_modules/
      - save_cache:
          name: Save cache (bower_components)
          key: bower_components-hack1-{{ checksum "bower.json" }}
          paths:
            - bower_components

      - run:
          name: Build
          command: yarn run build
      - store_artifacts:
          path: dist/
      - deploy:
          name: Deploy
          command: |
            if [ "$PREVIEW" == "true" ]
            then
              yarn run deploy -- --confirm --preview
            else
              yarn run deploy -- --confirm
            fi
